"""Light-cone-first white (P7-5, prototype): let a field travel on a causal set -- an ORDER, not a lattice.

A causal set gives only "who can influence whom" (the order ≺) and a density ρ (points per unit spacetime
volume). No distance, no grid, no speed of light is put in: the light cone IS the order. Here we put a field on it.

1) Retarded propagator by "hop and stop" (Johnston's causal-set propagator, 2D). Each element reads only its
   causal PAST and adds up what arrives:

        K(s, x) = ½·[s ≺ x] − (m²/2ρ) · Σ_{y: s ≺ y ≺ x} K(s, y)

   i.e. a sum over chains s ≺ y1 ≺ … ≺ x, each hop weighted −m²/(2ρ), each chain weighted ½. In the continuum
   (2D Minkowski, ρ → ∞) the mean of K is the retarded Green's function of (□ + m²):  ½·θ(inside the cone)·J0(mτ),
   τ the proper time. m = 0 gives ½ inside the cone (exact). What is PUT IN: the order (here generated by
   sprinkling into 2D Minkowski -- the coordinates are then forgotten), ρ, m, and the weights ½ and −m²/2ρ.
   What can GROW: the Bessel waviness (the field oscillates and changes sign with proper time) from nothing but
   counting chains.

2) The smeared causal-set d'Alembertian (Sorkin 2007; 2D), evaluated at an element x from the elements of its past
   and the number n of elements strictly between each y and x:

        B_ε φ(x) = (4ε/ℓ²) [ −½ φ(x) + ε Σ_{y ≺ x} f(n(y,x), ε) φ(y) ],   ℓ² = 1/ρ,
        f(n, ε) = (1−ε)^n [1 − 2εn/(1−ε) + ε² n(n−1)/(2(1−ε)²)]

   ε = ℓ²/ℓ_k² sets a nonlocality scale ℓ_k (put in). In the mean over sprinklings B_ε φ → □φ with
   □ = −∂t² + ∂x² (sign convention of the source); single sprinklings fluctuate strongly -- a known frontier.

"Local" here means order-local: each element reads its own causal past (no global solve, no FFT). That past is the
whole past cone, not a few neighbours -- on a causal set there are no nearest neighbours (the famous nonlocality).
"""
from __future__ import annotations

import numpy as np
from scipy.linalg import solve_triangular
from scipy.special import j0

from core.causet import causal_relation, sprinkle


def diamond_with_tips(N: int, seed: int) -> tuple[np.ndarray, np.ndarray]:
    """N sprinkled points in the unit 2D causal diamond (area ½, so ρ = 2N) plus its bottom tip (0,0) as element
    0 and its top tip (1,0) as the last element; all sorted by time (a linear extension of the order).
    Returns (coords, relation)."""
    pts = np.vstack([[0.0, 0.0], sprinkle(N, 2, "diamond", seed), [1.0, 0.0]])
    pts = pts[np.argsort(pts[:, 0], kind="stable")]
    return pts, causal_relation(pts)


def retarded_from(R: np.ndarray, rho: float, m: float, source: int) -> np.ndarray:
    """K(source, x) for every element x by the hop-and-stop rule; elements must be in a linear extension of the
    order (index order = some valid time order). Each x reads only its causal past."""
    a = m * m / rho
    K = np.zeros(R.shape[0])
    for x in range(source + 1, R.shape[0]):
        if R[source, x]:
            K[x] = 0.5 - 0.5 * a * K[R[:, x]].sum()
    return K


def retarded_matrix(R: np.ndarray, rho: float, m: float) -> np.ndarray:
    """The same propagator for all pairs at once, K = ½ C (I + (m²/2ρ) C)⁻¹, solved as K (I + (m²/2ρ) C) = C/2
    (a cross-check of the element-by-element rule, not the rule itself)."""
    C = R.astype(float)
    A = np.eye(len(C)) + 0.5 * m * m / rho * C              # upper triangular in a linear extension
    return solve_triangular(A.T, 0.5 * C.T, lower=True).T


def proper_time(coords: np.ndarray, source: int) -> np.ndarray:
    """τ from the source (0 outside its future cone) -- only for comparing with the continuum."""
    d = coords - coords[source]
    return np.sqrt(np.maximum(d[:, 0] ** 2 - d[:, 1] ** 2, 0.0)) * (d[:, 0] > 0)


def continuum_retarded(tau: np.ndarray, m: float) -> np.ndarray:
    """½ J0(m τ) inside the future cone (τ > 0), 0 elsewhere: the 2D retarded Green's function of □ + m²."""
    return np.where(tau > 0, 0.5 * j0(m * tau), 0.0)


def between_counts(R: np.ndarray, x: int) -> tuple[np.ndarray, np.ndarray]:
    """The past of x and, for each y in it, the number of elements strictly between y and x."""
    past = np.nonzero(R[:, x])[0]
    return past, R[np.ix_(past, past)].sum(1)


def smeared_box(R: np.ndarray, rho: float, eps: float, phi: np.ndarray, x: int) -> float:
    """B_ε φ(x) (see the module doc). phi: the field on every element."""
    past, n = between_counts(R, x)
    f = (1 - eps) ** n * (1 - 2 * eps * n / (1 - eps) + eps ** 2 * n * (n - 1) / (2 * (1 - eps) ** 2))
    return float(4 * eps * rho * (-0.5 * phi[x] + eps * (f * phi[past]).sum()))
