"""P3: move bulk generated data out of the working tree -- recoverably, never deleting history.

What leaves the working tree (decided by the P2 audit, docs/TREASURE_AUDIT.md):

    rooms/candidates/<room>/                  rooms classed "index-only" in audit/candidates.jsonl (whole dir)
    rooms/candidates/<room>/runs/*/field.json rooms classed "distill" (display frames; keyframes are in
                                              audit/candidates_keyframes.npz, the rest stays)
    app/public/data/**, app/generated/**      generated by tools/build_catalog.py + tools/collect_app_data.py
    ai_lab/reports/{nightly,easy}/20*/        timestamped bot reports, except the ones still referenced

Every removed file is recorded in archive/MANIFEST.jsonl.gz as {path, blob, size, reason} where ``blob`` is
the git blob id at ``source_commit`` (the commit the removal was made on top of). Nothing is lost:

    python tools/archive.py verify --sample 20        # blobs still resolve at source_commit
    python tools/archive.py restore rooms/candidates/room-auto-dream-20260807-0001-...   # bring files back

Usage for the removal itself (run once, on a clean checkout of main):

    python tools/archive.py apply                     # git rm + write manifest (then commit)
"""
from __future__ import annotations

import argparse
import gzip
import json
import random
import subprocess
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_MANIFEST = _REPO / "archive" / "MANIFEST.jsonl.gz"
_HEADER = _REPO / "archive" / "README.md"
# Timestamped report dirs still referenced by name (nightly/latest.json easy_report_paths, docs/INVENTORY).
_KEEP_REPORT_DIRS = {
    "ai_lab/reports/easy/2026-09-25T18-34-14Z",
    "ai_lab/reports/nightly/2026-08-07T07-09-57Z",
}


def _git(*args: str, stdin: str | None = None) -> str:
    return subprocess.run(["git", *args], cwd=_REPO, check=True, capture_output=True, text=True, input=stdin).stdout


def _tree(commit: str, *paths: str) -> list[tuple[str, str, int]]:
    """(path, blob, size) for every file under ``paths`` at ``commit``."""
    out = []
    for rec in _git("ls-tree", "-r", "-l", "-z", commit, "--", *paths).split("\0"):
        if not rec:
            continue
        meta, path = rec.split("\t", 1)
        _mode, _type, blob, size = meta.split()
        out.append((path, blob, int(size) if size.isdigit() else 0))
    return out


def plan(commit: str) -> list[dict]:
    rows = [json.loads(line) for line in (_REPO / "audit" / "candidates.jsonl").open(encoding="utf-8")]
    index_only = {r["room_id"] for r in rows if r["class"] == "index-only"}
    distill = {r["room_id"] for r in rows if r["class"] == "distill"}
    entries: list[dict] = []
    for path, blob, size in _tree(commit, "rooms/candidates"):
        room = path.split("/")[2] if path.count("/") >= 2 else None
        if room in index_only:
            entries.append({"path": path, "blob": blob, "size": size, "reason": "index-only room (audit/candidates.jsonl)"})
        elif room in distill and path.endswith("/field.json") and "/runs/" in path:
            entries.append({"path": path, "blob": blob, "size": size,
                            "reason": "distill room display frames (keyframes in audit/candidates_keyframes.npz)"})
    for path, blob, size in _tree(commit, "app/public/data", "app/generated"):
        entries.append({"path": path, "blob": blob, "size": size,
                        "reason": "generated app data (tools/build_catalog.py + tools/collect_app_data.py)"})
    for path, blob, size in _tree(commit, "ai_lab/reports/nightly", "ai_lab/reports/easy"):
        parts = path.split("/")
        if len(parts) >= 5 and parts[3].startswith("20") and "/".join(parts[:4]) not in _KEEP_REPORT_DIRS:
            entries.append({"path": path, "blob": blob, "size": size, "reason": "timestamped bot report"})
    return entries


def load_manifest() -> tuple[dict, list[dict]]:
    with gzip.open(_MANIFEST, "rt", encoding="utf-8") as fh:
        header = json.loads(fh.readline())
        return header, [json.loads(line) for line in fh]


def apply() -> None:
    if _git("status", "--porcelain", "--untracked-files=no").strip():
        sys.exit("working tree has tracked changes; commit or stash first")
    commit = _git("rev-parse", "HEAD").strip()
    entries = plan(commit)
    header = {"source_commit": commit, "files": len(entries), "bytes": sum(e["size"] for e in entries),
              "restore": "git restore --source=<source_commit> -- <path>  (or: python tools/archive.py restore <prefix>)"}
    _MANIFEST.parent.mkdir(exist_ok=True)
    with gzip.open(_MANIFEST, "wt", encoding="utf-8") as fh:
        fh.write(json.dumps(header, sort_keys=True) + "\n")
        for e in entries:
            fh.write(json.dumps(e, sort_keys=True) + "\n")
    paths = [e["path"] for e in entries]
    for i in range(0, len(paths), 2000):  # git rm in chunks (argv limits)
        subprocess.run(["git", "rm", "-q", "--cached", "--", *paths[i:i + 2000]], cwd=_REPO, check=True)
        for p in paths[i:i + 2000]:
            (_REPO / p).unlink(missing_ok=True)
    dirs = {str(parent) for p in paths for parent in Path(p).parents if str(parent) != "."}
    for d in sorted(dirs, key=lambda x: x.count("/"), reverse=True):  # prune now-empty dirs, deepest first
        try:
            (_REPO / d).rmdir()
        except OSError:
            pass
    print(json.dumps(header, indent=2))


def verify(sample: int, seed: int = 0) -> int:
    header, entries = load_manifest()
    commit = header["source_commit"]
    if subprocess.run(["git", "cat-file", "-e", f"{commit}^{{commit}}"], cwd=_REPO, capture_output=True).returncode:
        print(f"source commit {commit} not in local history (shallow clone?) -- fetch it first")
        return 2
    picked = random.Random(seed).sample(entries, min(sample, len(entries)))
    bad = 0
    for e in picked:
        got = _git("rev-parse", f"{commit}:{e['path']}").strip()
        size = int(_git("cat-file", "-s", got).strip())
        ok = got == e["blob"] and size == e["size"]
        bad += not ok
        print(f"{'OK ' if ok else 'BAD'} {e['path']}")
    print(f"{len(picked) - bad}/{len(picked)} archived files resolve to the recorded blob at {commit[:12]}")
    return 1 if bad else 0


def restore(prefixes: list[str]) -> None:
    header, entries = load_manifest()
    paths = [e["path"] for e in entries if any(e["path"].startswith(p) for p in prefixes)]
    if not paths:
        sys.exit("no archived path matches")
    for i in range(0, len(paths), 2000):
        subprocess.run(["git", "restore", f"--source={header['source_commit']}", "--", *paths[i:i + 2000]],
                       cwd=_REPO, check=True)
    print(f"restored {len(paths)} file(s) from {header['source_commit'][:12]} into the working tree (not staged)")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("plan", help="print what would be archived (sizes by reason)")
    sub.add_parser("apply", help="git rm the planned files and write archive/MANIFEST.jsonl.gz")
    v = sub.add_parser("verify", help="check sampled manifest entries against source_commit")
    v.add_argument("--sample", type=int, default=20)
    r = sub.add_parser("restore", help="restore archived files whose path starts with a prefix")
    r.add_argument("prefix", nargs="+")
    a = ap.parse_args()
    if a.cmd == "plan":
        entries = plan(_git("rev-parse", "HEAD").strip())
        by: dict[str, list[int]] = {}
        for e in entries:
            by.setdefault(e["reason"], [0, 0])
            by[e["reason"]][0] += 1
            by[e["reason"]][1] += e["size"]
        print(json.dumps({k: {"files": n, "MB": round(b / 2**20, 1)} for k, (n, b) in by.items()}, indent=2))
    elif a.cmd == "apply":
        apply()
    elif a.cmd == "verify":
        sys.exit(verify(a.sample))
    else:
        restore(a.prefix)


if __name__ == "__main__":
    main()
